name: media_key_detector
description: A Very Good Project created by Very Good CLI.
version: 0.0.2
homepage: https://github.com/holotrek/media_key_detector

environment:
  sdk: "^3.3.0"
  flutter: ">=3.19.3"

flutter:
  plugin:
    platforms:
      linux:
        default_package: media_key_detector_linux
      macos:
        default_package: media_key_detector_macos
      windows:
        default_package: media_key_detector_windows

dependencies:
  flutter:
    sdk: flutter

  media_key_detector_linux: ^0.0.1
  media_key_detector_macos: ^0.0.1
  media_key_detector_platform_interface: ^0.0.1
  media_key_detector_windows: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^5.1.0
