name: media_key_detector_windows
description: Windows implementation of the media_key_detector plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

flutter:
  plugin:
    implements: media_key_detector
    platforms:
      windows:
        pluginClass: MediaKeyDetectorWindows
        dartPluginClass: MediaKeyDetectorWindows

dependencies:
  flutter:
    sdk: flutter
  media_key_detector_platform_interface:
    path: ../media_key_detector_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
