name: media_key_detector_windows

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/media_key_detector_windows.yaml"
      - "media_key_detector_windows/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/media_key_detector_windows.yaml"
      - "media_key_detector_windows/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.19.0
      working_directory: media_key_detector_windows

