name: media_key_detector_platform_interface-ci-pr

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/media_key_detector_platform_interface-ci-pr.yml"
      - "media_key_detector_platform_interface/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/media_key_detector_platform_interface-ci-pr.yml"
      - "media_key_detector_platform_interface/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./media_key_detector_platform_interface
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.4"
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Format code
        run: dart format --fix .
      - name: Check Publish Warnings
        run: dart pub publish --dry-run
